"use client"

import { DeploymentPipeline } from "@/components/sections/production-ready/variants/deployment-pipeline"
import { GitActivityFeed } from "@/components/sections/production-ready/variants/git-activity-feed"
import { CodeQualityScorecard } from "@/components/sections/production-ready/variants/code-quality-scorecard"
import { SplitPreview } from "@/components/sections/production-ready/variants/split-preview"

export default function DashboardTestPage() {
  return (
    <main className="min-h-screen bg-background py-12">
      <div className="max-w-[1436px] mx-auto px-6 lg:px-[50px]">
        {/* Page Header */}
        <div className="mb-16 text-center">
          <span className="inline-flex items-center px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-sm font-medium mb-4">
            Production-Ready Section
          </span>
          <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
            Dashboard Variants
          </h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            4 design concepts for the "Production-ready from day one" section.
            Each visualizes real code being generated and deployed.
          </p>
        </div>

        {/* Variant 1: Deployment Pipeline */}
        <section className="mb-24">
          <div className="mb-8 pb-4 border-b border-border/50">
            <span className="inline-flex items-center px-3 py-1 rounded-full bg-amber-500/10 text-amber-500 text-sm font-medium mb-3">
              Variant 1
            </span>
            <h2 className="text-2xl font-semibold text-foreground">Deployment Pipeline</h2>
            <p className="text-muted-foreground mt-2">
              Visual pipeline: Code → Tests → Build → Deploy with status indicators
            </p>
          </div>
          <div className="p-6 sm:p-8 rounded-xl bg-card/30 border border-border/30">
            <DeploymentPipeline />
          </div>
        </section>

        {/* Variant 2: Git Activity Feed */}
        <section className="mb-24">
          <div className="mb-8 pb-4 border-b border-border/50">
            <span className="inline-flex items-center px-3 py-1 rounded-full bg-purple-500/10 text-purple-500 text-sm font-medium mb-3">
              Variant 2
            </span>
            <h2 className="text-2xl font-semibold text-foreground">Git Activity Feed</h2>
            <p className="text-muted-foreground mt-2">
              Timeline of commits generated by ProductOS with additions/deletions
            </p>
          </div>
          <div className="p-6 sm:p-8 rounded-xl bg-card/30 border border-border/30">
            <GitActivityFeed />
          </div>
        </section>

        {/* Variant 3: Code Quality Scorecard */}
        <section className="mb-24">
          <div className="mb-8 pb-4 border-b border-border/50">
            <span className="inline-flex items-center px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-sm font-medium mb-3">
              Variant 3
            </span>
            <h2 className="text-2xl font-semibold text-foreground">Code Quality Scorecard</h2>
            <p className="text-muted-foreground mt-2">
              Build metrics: Test coverage, TypeScript, Lighthouse, Bundle size, Build time
            </p>
          </div>
          <div className="p-6 sm:p-8 rounded-xl bg-card/30 border border-border/30">
            <CodeQualityScorecard />
          </div>
        </section>

        {/* Variant 4: Split Preview */}
        <section className="mb-24">
          <div className="mb-8 pb-4 border-b border-border/50">
            <span className="inline-flex items-center px-3 py-1 rounded-full bg-blue-500/10 text-blue-500 text-sm font-medium mb-3">
              Variant 4
            </span>
            <h2 className="text-2xl font-semibold text-foreground">Code + Live Preview</h2>
            <p className="text-muted-foreground mt-2">
              Side-by-side: Generated code on left, live rendered preview on right
            </p>
          </div>
          <div className="p-6 sm:p-8 rounded-xl bg-card/30 border border-border/30">
            <SplitPreview />
          </div>
        </section>

        {/* Footer */}
        <div className="text-center py-8 border-t border-border/50">
          <p className="text-sm text-muted-foreground">
            Internal test page — pick the best variant for the homepage
          </p>
        </div>
      </div>
    </main>
  )
}
