"use client"

import { motion, useInView } from "framer-motion"
import { useRef, useEffect, useState } from "react"
import { 
  Check, 
  ChevronRight, 
  FileCode2, 
  FolderOpen, 
  GitBranch, 
  Sparkles,
  Play,
  Circle,
  X,
  Minus,
  Square,
  Terminal
} from "lucide-react"

// Agent planning steps
const planningSteps = [
  { type: "thinking", text: "Analyzing requirements..." },
  { type: "plan", text: "Creating Dashboard component" },
  { type: "plan", text: "Setting up data fetching" },
  { type: "plan", text: "Adding StatsCard grid" },
  { type: "plan", text: "Implementing charts" },
  { type: "success", text: "Ready to deploy" },
]

// Code lines with syntax highlighting
const codeLines = [
  { indent: 0, tokens: [{ text: "// ", type: "comment" }, { text: "Generated by ProductOS", type: "comment" }] },
  { indent: 0, tokens: [{ text: "import", type: "keyword" }, { text: " { ", type: "punctuation" }, { text: "StatsCard", type: "type" }, { text: ", ", type: "punctuation" }, { text: "AreaChart", type: "type" }, { text: " } ", type: "punctuation" }, { text: "from", type: "keyword" }, { text: " ", type: "plain" }, { text: "'@/components/ui'", type: "string" }] },
  { indent: 0, tokens: [] },
  { indent: 0, tokens: [{ text: "export", type: "keyword" }, { text: " ", type: "plain" }, { text: "async", type: "keyword" }, { text: " ", type: "plain" }, { text: "function", type: "keyword" }, { text: " ", type: "plain" }, { text: "Dashboard", type: "function" }, { text: "() {", type: "punctuation" }] },
  { indent: 1, tokens: [{ text: "const", type: "keyword" }, { text: " metrics ", type: "plain" }, { text: "=", type: "operator" }, { text: " ", type: "plain" }, { text: "await", type: "keyword" }, { text: " ", type: "plain" }, { text: "getMetrics", type: "function" }, { text: "()", type: "punctuation" }] },
  { indent: 1, tokens: [] },
  { indent: 1, tokens: [{ text: "return", type: "keyword" }, { text: " (", type: "punctuation" }] },
  { indent: 2, tokens: [{ text: "<", type: "punctuation" }, { text: "div", type: "tag" }, { text: " ", type: "plain" }, { text: "className", type: "attr" }, { text: "=", type: "punctuation" }, { text: '"grid gap-6"', type: "string" }, { text: ">", type: "punctuation" }] },
  { indent: 3, tokens: [{ text: "<", type: "punctuation" }, { text: "StatsCard", type: "component" }] },
  { indent: 4, tokens: [{ text: "title", type: "attr" }, { text: "=", type: "punctuation" }, { text: '"Active Users"', type: "string" }] },
  { indent: 4, tokens: [{ text: "value", type: "attr" }, { text: "=", type: "punctuation" }, { text: "{metrics.users}", type: "expression" }] },
  { indent: 4, tokens: [{ text: "trend", type: "attr" }, { text: "=", type: "punctuation" }, { text: '"+12%"', type: "string" }] },
  { indent: 3, tokens: [{ text: "/>", type: "punctuation" }] },
  { indent: 3, tokens: [{ text: "<", type: "punctuation" }, { text: "AreaChart", type: "component" }, { text: " ", type: "plain" }, { text: "data", type: "attr" }, { text: "=", type: "punctuation" }, { text: "{metrics.revenue}", type: "expression" }, { text: " />", type: "punctuation" }] },
  { indent: 2, tokens: [{ text: "</", type: "punctuation" }, { text: "div", type: "tag" }, { text: ">", type: "punctuation" }] },
  { indent: 1, tokens: [{ text: ")", type: "punctuation" }] },
  { indent: 0, tokens: [{ text: "}", type: "punctuation" }] },
]

// File tree
const files = [
  { name: "dashboard.tsx", active: true },
  { name: "stats-card.tsx", active: false },
  { name: "area-chart.tsx", active: false },
]

// Token colors - theme-aware syntax highlighting
const tokenColors: Record<string, string> = {
  keyword: "text-teal-600 dark:text-teal-400",
  string: "text-emerald-600 dark:text-emerald-400",
  comment: "text-muted-foreground/50 dark:text-white/30",
  function: "text-sky-600 dark:text-sky-400",
  type: "text-amber-600 dark:text-amber-400",
  component: "text-orange-600 dark:text-orange-400",
  tag: "text-sky-600 dark:text-sky-400",
  attr: "text-teal-600 dark:text-teal-400",
  punctuation: "text-foreground/50 dark:text-white/50",
  operator: "text-orange-600 dark:text-orange-400",
  expression: "text-amber-700 dark:text-amber-300",
  plain: "text-foreground/70 dark:text-white/70",
}

export function CursorStyleIDE() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: "-100px" })
  const [currentPlanStep, setCurrentPlanStep] = useState(0)
  const [currentCodeLine, setCurrentCodeLine] = useState(0)
  const [isGenerating, setIsGenerating] = useState(true)
  const [showDeployButton, setShowDeployButton] = useState(false)

  useEffect(() => {
    if (!isInView) return

    // Animate planning steps
    const planInterval = setInterval(() => {
      setCurrentPlanStep(prev => {
        if (prev >= planningSteps.length - 1) {
          clearInterval(planInterval)
          return prev
        }
        return prev + 1
      })
    }, 800)

    // Animate code generation (slightly faster than planning)
    const codeInterval = setInterval(() => {
      setCurrentCodeLine(prev => {
        if (prev >= codeLines.length - 1) {
          clearInterval(codeInterval)
          setIsGenerating(false)
          setTimeout(() => setShowDeployButton(true), 500)
          return prev
        }
        return prev + 1
      })
    }, 400)

    return () => {
      clearInterval(planInterval)
      clearInterval(codeInterval)
    }
  }, [isInView])

  return (
    <div ref={ref} className="relative">
      {/* Linear-style reflection gradient beneath dashboard (dark mode only) */}
      <div 
        className="absolute inset-x-3 inset-y-0 rounded-2xl pointer-events-none hidden dark:block"
        style={{
          background: `
            radial-gradient(52% 58% at 50% 100%, rgba(10, 10, 11, 0) 0%, rgba(10, 10, 11, 0.6) 100%),
            linear-gradient(to bottom, rgb(10, 10, 11) 10%, rgb(45, 50, 58) 100%)
          `
        }}
      />
      
      {/* Main dashboard container - theme-aware */}
      <div 
        className="relative rounded-2xl overflow-hidden bg-card dark:bg-[#09090a] border border-border dark:border-white/[0.08] shadow-lg"
      >
        {/* Inner frame */}
        <div className="relative rounded-xl overflow-hidden bg-muted/30 dark:bg-[#0a0a0a]">
          {/* Glossy shine overlay - radial mask like Linear (dark mode only) */}
          <div 
            className="absolute inset-0 pointer-events-none z-10 hidden dark:block"
            style={{
              background: 'linear-gradient(180deg, rgba(255,255,255,0.06) 0%, rgba(255,255,255,0.02) 20%, transparent 40%)',
              mask: 'radial-gradient(180px 180px at 10% 0%, black 0%, rgba(0,0,0,0.5) 40%, transparent 70%)',
              WebkitMask: 'radial-gradient(180px 180px at 10% 0%, black 0%, rgba(0,0,0,0.5) 40%, transparent 70%)'
            }}
          />
          
          {/* Top edge highlight */}
          <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-black/5 dark:via-white/15 to-transparent pointer-events-none z-10" />
          
          {/* Subtle ambient glow - matching first dashboard (dark mode only) */}
          <div 
            className="absolute inset-0 pointer-events-none hidden dark:block"
            style={{
              background: `
                radial-gradient(ellipse 70% 40% at 50% 0%, rgba(255, 255, 255, 0.04) 0%, transparent 50%),
                radial-gradient(ellipse 50% 30% at 80% 10%, rgba(255, 255, 255, 0.025) 0%, transparent 40%)
              `
            }}
          />
        {/* Window Chrome - Linear-style minimal */}
        <div className="flex items-center justify-between px-4 py-3 bg-muted/30 dark:bg-white/[0.02] border-b border-border/50 dark:border-white/[0.06]">
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-sm font-medium text-foreground dark:text-white">ProductOS Code</span>
          </div>
          <div className="flex items-center gap-2 px-3 py-1 rounded-md bg-muted dark:bg-white/[0.04] border border-border/50 dark:border-white/[0.06]">
            <FolderOpen className="w-3.5 h-3.5 text-muted-foreground dark:text-white/50" />
            <span className="text-xs text-muted-foreground dark:text-white/60 font-mono">my-saas-app</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1.5 px-2 py-0.5 rounded bg-muted dark:bg-white/[0.04] border border-border/50 dark:border-white/[0.06]">
              <GitBranch className="w-3 h-3 text-muted-foreground dark:text-white/50" />
              <span className="text-xs text-muted-foreground dark:text-white/50 font-mono">main</span>
            </div>
          </div>
        </div>

        {/* Main Content - Split View */}
        <div className="flex min-h-[400px]">
          {/* Left Panel - Agent Planning */}
          <div className="w-[280px] border-r border-border/50 dark:border-white/[0.06] bg-muted/50 dark:bg-[#0f0f10] flex flex-col">
            {/* Panel Header - Linear-style */}
            <div className="flex items-center gap-2 px-3 py-2 border-b border-border/30 dark:border-white/[0.04]">
              <div className="p-1 rounded bg-muted dark:bg-white/[0.06] border border-border/50 dark:border-white/[0.08]">
                <Sparkles className="w-3.5 h-3.5 text-muted-foreground dark:text-white/60" />
              </div>
              <span className="text-xs font-medium text-foreground dark:text-white">ProductOS Agent</span>
              {isGenerating && (
                <motion.div
                  animate={{ opacity: [0.5, 1, 0.5] }}
                  transition={{ duration: 1.5, repeat: Infinity }}
                  className="ml-auto w-1.5 h-1.5 rounded-full bg-foreground/60 dark:bg-white/60"
                />
              )}
            </div>

            {/* Planning Steps */}
            <div className="flex-1 p-3 overflow-y-auto">
              <div className="space-y-2">
                {planningSteps.map((step, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{
                      opacity: index <= currentPlanStep ? 1 : 0,
                      x: index <= currentPlanStep ? 0 : -10,
                    }}
                    transition={{ duration: 0.2 }}
                    className="flex items-start gap-2"
                  >
                    {step.type === "thinking" ? (
                      <motion.div
                        animate={index === currentPlanStep && isGenerating ? { rotate: 360 } : {}}
                        transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                        className="mt-0.5"
                      >
                        <Circle className="w-3.5 h-3.5 text-muted-foreground dark:text-white/50" />
                      </motion.div>
                    ) : step.type === "success" ? (
                      <Check className="w-3.5 h-3.5 mt-0.5 text-emerald-600 dark:text-emerald-500" />
                    ) : (
                      <ChevronRight className="w-3.5 h-3.5 mt-0.5 text-muted-foreground dark:text-white/40" />
                    )}
                    <span className={`text-xs ${
                      step.type === "thinking" ? "text-muted-foreground dark:text-white/60" :
                      step.type === "success" ? "text-emerald-600 dark:text-emerald-400" :
                      "text-muted-foreground dark:text-white/50"
                    }`}>
                      {step.text}
                    </span>
                  </motion.div>
                ))}
              </div>

              {/* File Output */}
              {currentPlanStep >= 2 && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="mt-4 pt-3 border-t border-border/30 dark:border-white/[0.04]"
                >
                  <span className="text-[10px] uppercase tracking-wider text-muted-foreground/60 dark:text-white/30 font-medium">Generated Files</span>
                  <div className="mt-2 space-y-1">
                    {files.map((file, index) => (
                      <motion.div
                        key={file.name}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: index <= currentPlanStep - 2 ? 1 : 0.3 }}
                        className={`flex items-center gap-2 px-2 py-1.5 rounded text-xs ${
                          file.active ? "bg-muted dark:bg-white/[0.04] text-foreground dark:text-white" : "text-muted-foreground dark:text-white/50"
                        }`}
                      >
                        <FileCode2 className="w-3.5 h-3.5" />
                        <span className="font-mono">{file.name}</span>
                        {index <= currentPlanStep - 2 && (
                          <Check className="w-3 h-3 ml-auto text-emerald-600 dark:text-emerald-500" />
                        )}
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              )}
            </div>
          </div>

          {/* Right Panel - Code Editor */}
          <div className="flex-1 flex flex-col bg-background dark:bg-[#0a0a0a]">
            {/* File Tabs - Linear-style */}
            <div className="flex items-center border-b border-border/30 dark:border-white/[0.04] bg-muted/20 dark:bg-white/[0.01]">
              <div className="flex items-center gap-2 px-4 py-2 border-r border-border/30 dark:border-white/[0.04] bg-muted/50 dark:bg-white/[0.02]">
                <FileCode2 className="w-3.5 h-3.5 text-muted-foreground dark:text-white/50" />
                <span className="text-xs text-foreground dark:text-white font-mono">dashboard.tsx</span>
                <X className="w-3 h-3 text-muted-foreground hover:text-foreground dark:text-white/30 dark:hover:text-white/60 cursor-pointer" />
              </div>
              <div className="flex-1" />
              {showDeployButton && (
                <motion.button
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="flex items-center gap-1.5 mr-3 px-3 py-1 rounded-md bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-medium transition-colors"
                >
                  <Play className="w-3 h-3" />
                  Deploy
                </motion.button>
              )}
            </div>

            {/* Code Content */}
            <div className="flex-1 overflow-hidden">
              <div className="p-4 font-mono text-[13px] leading-6">
                {codeLines.map((line, lineIndex) => (
                  <motion.div
                    key={lineIndex}
                    initial={{ opacity: 0 }}
                    animate={{
                      opacity: lineIndex <= currentCodeLine ? 1 : 0.15,
                    }}
                    transition={{ duration: 0.1 }}
                    className="flex"
                  >
                    {/* Line number */}
                    <span className="w-8 text-right pr-4 text-muted-foreground/50 dark:text-white/30 select-none text-xs">
                      {lineIndex + 1}
                    </span>
                    {/* Code with indent */}
                    <span style={{ paddingLeft: `${line.indent * 16}px` }}>
                      {line.tokens.map((token, tokenIndex) => (
                        <span key={tokenIndex} className={tokenColors[token.type]}>
                          {token.text}
                        </span>
                      ))}
                    </span>
                    {/* Typing cursor - Linear-style subtle */}
                    {lineIndex === currentCodeLine && isGenerating && (
                      <motion.span
                        animate={{ opacity: [1, 0] }}
                        transition={{ duration: 0.5, repeat: Infinity }}
                        className="w-0.5 h-4 ml-0.5 bg-foreground/70 dark:bg-white/70 inline-block"
                      />
                    )}
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Status Bar */}
            <div className="flex items-center justify-between px-4 py-1.5 border-t border-border/30 dark:border-white/[0.04] bg-muted/30 dark:bg-white/[0.02] text-[10px]">
              <div className="flex items-center gap-3 text-muted-foreground dark:text-white/40">
                <span>TypeScript React</span>
                <span>•</span>
                <span>UTF-8</span>
                <span>•</span>
                <span>Ln {currentCodeLine + 1}</span>
              </div>
              <div className="flex items-center gap-2">
                {!isGenerating && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400"
                  >
                    <Check className="w-3 h-3" />
                    <span>All checks passed</span>
                  </motion.div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Terminal / Output (collapsed) */}
        <div className="border-t border-border/30 dark:border-white/[0.04] bg-muted/20 dark:bg-white/[0.01]">
          <div className="flex items-center justify-between px-4 py-2">
            <div className="flex items-center gap-2 text-muted-foreground dark:text-white/40">
              <Terminal className="w-3.5 h-3.5" />
              <span className="text-xs font-medium">Output</span>
            </div>
            {showDeployButton && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex items-center gap-2"
              >
                <div className="relative">
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                  <div className="absolute inset-0 w-1.5 h-1.5 rounded-full bg-emerald-500 animate-ping" />
                </div>
                <span className="text-xs text-muted-foreground dark:text-white/50">
                  <span className="text-emerald-600 dark:text-emerald-400">✓</span> Build successful • Ready to deploy
                </span>
              </motion.div>
            )}
          </div>
        </div>
        {/* Close inner frame */}
        </div>
        {/* Close main dashboard container */}
      </div>
      {/* Close outer wrapper */}
    </div>
  )
}
