"use client"

import { motion } from "framer-motion"
import { CheckCircle2, Code2, TestTube2, Package, Rocket, ExternalLink } from "lucide-react"

const codeSnippet = `// Generated by ProductOS
export async function createUser(data: UserInput) {
  const validated = UserSchema.parse(data)
  return await db.user.create({ data: validated })
}`

const pipelineSteps = [
  {
    icon: Code2,
    label: "Code Generated",
    status: "complete",
    detail: "TypeScript + Next.js",
  },
  {
    icon: TestTube2,
    label: "Tests Passing",
    status: "complete",
    detail: "24/24 passed",
  },
  {
    icon: Package,
    label: "Build Complete",
    status: "complete",
    detail: "142kb bundle",
  },
  {
    icon: Rocket,
    label: "Deployed",
    status: "complete",
    detail: "Vercel Edge",
  },
]

export function DeploymentPipeline() {
  return (
    <div className="w-full">
      {/* Code Preview */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.4 }}
        className="mb-6 p-4 rounded-lg bg-muted/30 border border-border/50 font-mono text-xs sm:text-sm overflow-x-auto"
      >
        <pre className="text-muted-foreground whitespace-pre-wrap break-words">
          <code>{codeSnippet}</code>
        </pre>
      </motion.div>

      {/* Pipeline Steps */}
      <div className="relative">
        {/* Connection Line - Desktop */}
        <div className="hidden md:block absolute top-8 left-[10%] right-[10%] h-px bg-border" />
        
        {/* Connection Line - Mobile (vertical) */}
        <div className="md:hidden absolute left-8 top-[10%] bottom-[10%] w-px bg-border" />

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 md:gap-2">
          {pipelineSteps.map((step, index) => (
            <motion.div
              key={step.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
              className="relative flex md:flex-col items-center md:items-center gap-4 md:gap-2 p-4 md:p-3"
            >
              {/* Step Circle */}
              <div className="relative z-10 flex-shrink-0">
                <motion.div
                  initial={{ scale: 0.8 }}
                  whileInView={{ scale: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.3, delay: index * 0.1 + 0.2 }}
                  className="w-16 h-16 rounded-xl bg-card border border-border flex items-center justify-center"
                >
                  <step.icon className="w-6 h-6 text-foreground/70" />
                </motion.div>
                
                {/* Check Badge */}
                <motion.div
                  initial={{ scale: 0, opacity: 0 }}
                  whileInView={{ scale: 1, opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.3, delay: index * 0.1 + 0.4 }}
                  className="absolute -top-1 -right-1"
                >
                  <CheckCircle2 className="w-5 h-5 text-emerald-500 fill-emerald-500/20" />
                </motion.div>
              </div>

              {/* Step Content */}
              <div className="flex-1 md:text-center">
                <p className="font-medium text-sm text-foreground">{step.label}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{step.detail}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Live URL Indicator */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.4, delay: 0.6 }}
        className="mt-6 flex items-center justify-center gap-3 p-4 rounded-lg bg-emerald-500/5 border border-emerald-500/20"
      >
        <div className="relative">
          <div className="w-2 h-2 rounded-full bg-emerald-500" />
          <div className="absolute inset-0 w-2 h-2 rounded-full bg-emerald-500 animate-ping" />
        </div>
        <span className="text-sm font-medium text-emerald-500">Live</span>
        <span className="text-sm text-muted-foreground">your-app.vercel.app</span>
        <ExternalLink className="w-3.5 h-3.5 text-muted-foreground" />
      </motion.div>
    </div>
  )
}
